on:
  push:
    branches:
      - main
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Temporarily move the script to a different location
      - name: Move script to a temporary location
        run: |
          mkdir -p .tmp/
          mv delete_missing_files.py .tmp/

      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          remote_path: '/'
          sftp_only: true

      # Move the script back to its original location
      - name: Restore script from the temporary location
        run: |
          mv .tmp/delete_missing_files.py .
          rmdir .tmp/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko
      - name: Delete missing files in SFTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: python delete_missing_files.py
